alias la='ls -la'
alias rtmux='tmux source ~/.config/tmux/tmux.conf'
alias rbash='source ~/.bashrc'
alias ktmux='tmux kill-server'
alias atmux='tmux attach -t '
alias gitgraph='git log --oneline --all --graph'
alias cnvim='nvim ~/.config/nvim'
alias ctmux='nvim ~/.config/tmux'
alias ci3='nvim ~/.config/i3'
alias rpanel='pkill xfce4-panel; sleep .5; xfce4-panel &'
alias cityu-vpn='$HOME/.venvs/gp-saml/bin/gp-saml-gui -P --gateway --clientos=Windows ivpn.cityu.edu.hk --allow-insecure-crypto -- --csd-wrapper=/usr/libexec/openconnect/hipreport.sh'
